CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    seat_number INTEGER NOT NULL,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT fk_seats_event
        FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT uk_seats_event_seat_number
        UNIQUE (event_id, seat_number),
    CONSTRAINT ck_seats_status
        CHECK (status IN ('AVAILABLE', 'RESERVED'))
);

CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat_id BIGINT NOT NULL,
    customer_id VARCHAR(255) NOT NULL,
    CONSTRAINT fk_reservations_seat
        FOREIGN KEY (seat_id) REFERENCES seats (id),
    CONSTRAINT uk_reservations_seat UNIQUE (seat_id)
);
